---

- name: Enable Logrotate
  template:
    src:   etc/logrotate.d/vhost.conf.j2
    dest:  "/etc/logrotate.d/openresty-vhosts"
    owner: "root"
    group: "root"
    mode:  "0644"

# vi:ts=2:sw=2:et:ft=yaml
